// Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
// SPDX-License-Identifier: Apache-2.0
/** Generated by rushx gen-i18n-types */
/* eslint-disable max-lines -- skip */
import { type ReactNode } from 'react';

/** I18n with interpolation */
export interface I18nWithInterpolation {
  /** {num, plural, other {{num}天（{date}）}} */
  expired_time_days_1: {
    /** number */
    num: ReactNode;
    /** string */
    date: ReactNode;
  };
  /** 获取元数据信息失败：{msg} */
  fornax_analytics_fetch_meta_error: {
    /** string */
    msg: ReactNode;
  };
  /** 输入Tokens: {count}  */
  fornax_analytics_input_tokens_count: {
    /** string */
    count: ReactNode;
  };
  /** 输出Tokens: {count} */
  fornax_analytics_output_tokens_count: {
    /** string */
    count: ReactNode;
  };
  /** 推理Tokens: {count} */
  fornax_analytics_reasoning_tokens_count: {
    /** string */
    count: ReactNode;
  };
  /** 过去 {count} 天 */
  fornax_analytics_time_last_days: {
    /** string */
    count: ReactNode;
  };
  /** 过去 {count} 小时 */
  fornax_analytics_time_last_hours: {
    /** string */
    count: ReactNode;
  };
  /** 过去{count}分钟 */
  fornax_analytics_time_last_minutes: {
    /** string */
    count: ReactNode;
  };
  /** {field}已存在 */
  field_exists: {
    /** string */
    field: ReactNode;
  };
  /** {field}必填 */
  field_is_required: {
    /** string */
    field: ReactNode;
  };
  /** {field}不能为空 */
  field_not_empty: {
    /** string */
    field: ReactNode;
  };
  /** 请添加{field} */
  please_add: {
    /** string */
    field: ReactNode;
  };
  /** 请同意{field} */
  please_agree: {
    /** string */
    field: ReactNode;
  };
  /** 请配置{field} */
  please_configure: {
    /** string */
    field: ReactNode;
  };
  /** 请输入{field} */
  please_input: {
    /** string */
    field: ReactNode;
  };
  /** 请选择{field} */
  please_select: {
    /** string */
    field: ReactNode;
  };
  /** 请先同意{agreement} */
  please_agree_first: {
    /** string */
    agreement: ReactNode;
  };
  /** {num}天 */
  x_days: {
    /** number */
    num: ReactNode;
  };
  /** 字数: {num} */
  num_words: {
    /** string */
    num: ReactNode;
  };
  /** 对照组{index} */
  control_group_index: {
    /** string */
    index: ReactNode;
  };
  /** 最多上传{num}张图片 */
  max_upload_picture_num: {
    /** string */
    num: ReactNode;
  };
  /** 图片大小不能超过{num}MB */
  image_size_not_exceed_num_mb: {
    /** string */
    num: ReactNode;
  };
  /** 模拟消息组-{key} */
  mock_message_group: {
    /** string */
    key: ReactNode;
  };
  /** 百科知识数据集 {index} */
  pedia_dataset: {
    /** string */
    index: ReactNode;
  };
  /** 版本号必须大于当前版本号：{version} */
  version_number_gt_current: {
    /** string */
    version: ReactNode;
  };
  /** 草稿已自动保存于{date} */
  draft_auto_saved_date: {
    /** string */
    date: ReactNode;
  };
  /** 描述：{desc} */
  description_is: {
    /** string */
    desc: ReactNode;
  };
  /** 复制{name}配置，并新建评估器 */
  copy_record_name_config_and_create_new_evaluator: {
    /** string */
    name: ReactNode;
  };
  /** 确定删除评估器：{name}？ */
  confirm_delete_evaluator: {
    /** string */
    name: ReactNode;
  };
  /** 实验组 {index} */
  experimental_group_index: {
    /** string */
    index: ReactNode;
  };
  /** 对比{num}个实验 */
  compare_x_experiments: {
    /** number */
    count: ReactNode;
    /** string */
    num: ReactNode;
  };
  /** {num, plural, zero {无} other {#条}} */
  x_items : {
    /** number */
    item: ReactNode;
  };
  /** 稍等几秒后{refresh}页面查看 */
  wait_and_refresh_page: {
    /** string */
    refresh: ReactNode;
  };
  /** 单次最多添加{num}条数据项 */
  single_max_add_data_items: {
    /** string */
    num: ReactNode;
  };
  /** 数据项 {index} */
  data_item_index: {
    /** string */
    index: ReactNode;
  };
  /** 确认删除{num}列，此操作不可逆 */
  confirm_delete_x_columns: {
    /** string */
    num: ReactNode;
  };
  /** 最多支持{num}列 */
  max_support_columns: {
    /** string */
    num: ReactNode;
  };
  /** 请输入大于等于{num}的数字 */
  input_num_gte: {
    /** string */
    num: ReactNode;
  };
  /** 请输入小于等于{num}的数字 */
  input_num_lte: {
    /** string */
    num: ReactNode;
  };
  /** 仅支持精确到小数点后{precision}位 */
  support_precision: {
    /** string */
    precision: ReactNode;
  };
  /** 原因：{reason} */
  reason_is: {
    /** string */
    reason: ReactNode;
  };
  /** 最多保留小数点后{num}位 */
  keep_precision_num: {
    /** string */
    num: ReactNode;
  };
  /** 确认批量删除 {num} 条实验数据吗？此修改将不可逆。 */
  confirm_batch_delete_x_experiment: {
    /** string */
    num: ReactNode;
  };
  /** 实验对比最大数量不能超过 {num} 个，请重新选择。 */
  experiment_comparison_max_number: {
    /** string */
    num: ReactNode;
  };
  /** 最多展示{num}个视图 */
  max_display_view_num: {
    /** string */
    num: ReactNode;
  };
  /** 名称长度不能超过{num}个字符 */
  name_length_limit: {
    /** string */
    num: ReactNode;
  };
}

/** I18n keys without interpolation */
export type I18nKeysNoInterpolation =
  | 'actions'
  | 'add_api_token_1'
  | 'add_new_pat_1'
  | 'add_new_token_button_1'
  | 'add'
  | 'analytics_image_error'
  | 'analytics_trace_arguments'
  | 'analytics_trace_description'
  | 'analytics_trace_metadata'
  | 'analytics_trace_run'
  | 'analytics_trace_runtime'
  | 'analytics_trace_type'
  | 'api_status_1'
  | 'api_status_active_1'
  | 'api_status_expired_1'
  | 'api_status_permanent_1'
  | 'auth_tab_pat'
  | 'Cancel'
  | 'cancel'
  | 'code'
  | 'Confirm'
  | 'confirm'
  | 'Content'
  | 'Copy'
  | 'copy'
  | 'coze_api_instru'
  | 'coze_api_list1'
  | 'coze_api_list3'
  | 'coze_api_list4'
  | 'coze_api_list5'
  | 'creators'
  | 'customize_key_1'
  | 'delete_desc'
  | 'delete_title'
  | 'Delete'
  | 'delete'
  | 'Description'
  | 'edit_pat_1'
  | 'Edit'
  | 'error'
  | 'expand'
  | 'expire_time_1'
  | 'expired_time_forbidden_1'
  | 'failed'
  | 'fornax_analytics_collapse'
  | 'fornax_analytics_copy_fail'
  | 'fornax_analytics_copy_success'
  | 'fornax_analytics_data_empty'
  | 'fornax_analytics_empty_data_abnormal'
  | 'fornax_analytics_empty_node_unselected'
  | 'fornax_analytics_empty_run_tree_failure'
  | 'fornax_analytics_empty_to_select_node'
  | 'fornax_analytics_extend'
  | 'fornax_analytics_query_detail_span_id'
  | 'fornax_analytics_range_this_month'
  | 'fornax_analytics_status_code'
  | 'fornax_analytics_tab_run_tree'
  | 'fornax_analytics_threads_options_dev'
  | 'fornax_analytics_threads_options_fail'
  | 'fornax_analytics_threads_options_online'
  | 'fornax_analytics_threads_options_success'
  | 'fornax_analytics_time_day_before_yesterday'
  | 'fornax_analytics_time_past_3_months'
  | 'fornax_analytics_time_past_month'
  | 'fornax_analytics_time_past_week'
  | 'fornax_analytics_time_past_year'
  | 'fornax_analytics_time_today_so_far'
  | 'fornax_analytics_time_week_so_far'
  | 'fornax_analytics_time_yesterday'
  | 'fornax_analytics_title_span_detail'
  | 'fornax_components_logic_expr_add_filter_group'
  | 'fornax_components_logic_expr_add_filter'
  | 'fornax_components_logic_expr_and'
  | 'fornax_components_logic_expr_delete_filter'
  | 'fornax_components_logic_expr_not'
  | 'fornax_components_logic_expr_or'
  | 'go'
  | 'import'
  | 'Input'
  | 'language'
  | 'latest_version'
  | 'loaded'
  | 'loading'
  | 'Loading'
  | 'logout'
  | 'Me'
  | 'mobile'
  | 'model_family'
  | 'model_info'
  | 'model_name'
  | 'new_pat_1'
  | 'next'
  | 'no_api_token_1'
  | 'or'
  | 'Output'
  | 'parameters'
  | 'pat_reminder_1'
  | 'pat_reminder_2'
  | 'platform_name'
  | 'Plugins'
  | 'prompt_generate_instruction_validate'
  | 'prompt_generate_statement_validate'
  | 'prompt_generate_stop_responding'
  | 'prompt_generate_stop'
  | 'prompt_submit'
  | 'prompt_version_submit'
  | 'python'
  | 'replace'
  | 'required'
  | 'Responding'
  | 'Retry'
  | 'retry'
  | 'Save'
  | 'Search'
  | 'select_expired_time_1'
  | 'space'
  | 'Success'
  | 'task_filter_eq'
  | 'task_filter_gt'
  | 'task_filter_gte'
  | 'task_filter_in'
  | 'task_filter_is_null'
  | 'task_filter_like'
  | 'task_filter_lt'
  | 'task_filter_lte'
  | 'task_filter_not_eq'
  | 'task_filter_not_in'
  | 'task_filter_not_null'
  | 'template_name'
  | 'text'
  | 'Tools'
  | 'Type'
  | 'type'
  | 'undefined'
  | 'user_info_custom_name'
  | 'user_info_email'
  | 'user_info_username'
  | 'version'
  | 'Workflow'
  | 'account'
  | 'back'
  | 'clear'
  | 'collapse'
  | 'debug'
  | 'demo_space'
  | 'description'
  | 'detail'
  | 'email'
  | 'experiment'
  | 'field'
  | 'login'
  | 'name'
  | 'network_error'
  | 'operation'
  | 'password'
  | 'permanent'
  | 'preview'
  | 'refresh'
  | 'register'
  | 'remove'
  | 'retrying'
  | 'run'
  | 'save'
  | 'submit'
  | 'today'
  | 'tomorrow'
  | 'user_agreement'
  | 'unknown_error'
  | 'yesterday'
  | 'search_creator'
  | 'current_user'
  | 'reset_to_default'
  | 'drag_to_sort'
  | 'column_management'
  | 'copy_id'
  | 'copy_success'
  | 'copy_failed'
  | 'view_detail'
  | 'page_not_found'
  | 'page_load_failed'
  | 'no_permission'
  | 'click_ascending'
  | 'click_descending'
  | 'restore_default_sort'
  | 'copy_content'
  | 'save_time'
  | 'current_draft'
  | 'submit_time'
  | 'submitter'
  | 'version_description'
  | 'version_record'
  | 'space_not_exists'
  | 'click_retry'
  | 'document'
  | 'lark_group'
  | 'prompt_engineering'
  | 'prompt_development'
  | 'evaluation'
  | 'evaluation_set'
  | 'evaluator'
  | 'observation'
  | 'confirm_logout'
  | 'account_settings'
  | 'no_space'
  | 'not_join_space'
  | 'api_authorization'
  | 'welcome_to_cozeloop'
  | 'please_input_email'
  | 'please_input_password'
  | 'token_show_only_once'
  | 'expiration_time'
  | 'token'
  | 'delete_token'
  | 'remove_will_affect_all_in_use'
  | 'register_or_login_failed'
  | 'prompt'
  | 'please_input_with_vars'
  | 'temperature'
  | 'max_tokens'
  | 'top_p'
  | 'top_k'
  | 'presence_penalty'
  | 'frequency_penalty'
  | 'edit_prompt'
  | 'create_copy'
  | 'create_prompt'
  | 'prompt_key'
  | 'prompt_key_format'
  | 'prompt_name'
  | 'prompt_name_format'
  | 'prompt_description'
  | 'prompt_var_format'
  | 'placeholder_var_name'
  | 'placeholder_format'
  | 'placeholder_name_exists'
  | 'placeholder_var_error'
  | 'historical_data_has_empty_content'
  | 'add_prompt_tpl_or_input_question'
  | 'set_to_reference_group'
  | 'delete_control_group'
  | 'load_more'
  | 'no_debug_record'
  | 'debug_history'
  | 'delete_prompt_template'
  | 'confirm_delete_current_prompt_template'
  | 'mock_value'
  | 'deeply_thought'
  | 'deep_thinking'
  | 'edit'
  | 'delete_message'
  | 'confirm_delete_message'
  | 'rerun'
  | 'delete_success'
  | 'delete_prompt'
  | 'copy_prompt_key'
  | 'prompt_key_again_confirm'
  | 'orchestration'
  | 'collapse_model_and_var_area'
  | 'expand_model_and_var_area'
  | 'expand_preview_and_debug'
  | 'collapse_preview_and_debug'
  | 'no_draft_change'
  | 'submitted'
  | 'placeholder_var_create_error'
  | 'model_id'
  | 'submission_no_version_diff'
  | 'open_enable_function'
  | 'close_enable_function'
  | 'continue'
  | 'close'
  | 'input_version_number'
  | 'image_upload_error'
  | 'clear_history_messages'
  | 'input_question_tip'
  | 'delete_function'
  | 'confirm_delete_function'
  | 'method_exists'
  | 'new_function'
  | 'method_name_rule'
  | 'input_mock_value_here'
  | 'trace_id'
  | 'copy_trace_id'
  | 'copy_variable_name'
  | 'delete_variable'
  | 'confirm_delete_var_in_tpl'
  | 'param_value'
  | 'mock_message'
  | 'system_role'
  | 'assistant_role'
  | 'user_role'
  | 'rollback_success'
  | 'restore_to_this_version'
  | 'restore_version_tip'
  | 'restore'
  | 'model_run_error'
  | 'model_runtime_error'
  | 'prompt_id_inconsistent'
  | 'recent_submission_time'
  | 'search_prompt_key_or_prompt_name'
  | 'no_prompt'
  | 'prompt_version_number_needed'
  | 'incorrect_version_number'
  | 'version_number_lt_error'
  | 'compact_view'
  | 'loose_view'
  | 'draft_version'
  | 'modify_not_submitted'
  | 'go_submit'
  | 'select_experiment'
  | 'initiate_experiment_comparison'
  | 'only_experiments_with_same_evaluation_set_and_completed_can_be_compared'
  | 'selected'
  | 'creator'
  | 'evaluation_object_type'
  | 'evaluation_object'
  | 'coze_bot'
  | 'coze_agent'
  | 'evaluation_set_version'
  | 'status'
  | 'this_is_a_cozebot'
  | 'view_actual_output_trace'
  | 'experiment_name'
  | 'the_field_required'
  | 'experiment_description'
  | 'edit_experiment'
  | 'choose_model'
  | 'check_parameters'
  | 'no_data'
  | 'associated_experiment'
  | 'evaluator_type'
  | 'model_selection'
  | 'preview_and_debug'
  | 'construct_test_data_to_preview_evaluator_runtime_result'
  | 'config_info'
  | 'construct_test_data'
  | 'testrun_require_fee'
  | 'generated_by_ai_tip'
  | 'evaluator_lacks_input'
  | 'information_unsaved'
  | 'leave_page_tip'
  | 'new_evaluator'
  | 'create'
  | 'confirm_clear_prompt'
  | 'system_prompt_not_empty'
  | 'delete_user_prompt'
  | 'confirm_delete_user_prompt'
  | 'add_user_prompt'
  | 'submit_new_version'
  | 'create_evaluator'
  | 'version_number_format'
  | 'version_number'
  | 'select_template'
  | 'preset_evaluator'
  | 'edit_evaluator'
  | 'draft_auto_saving'
  | 'draft_auto_save_failed'
  | 'submission_time'
  | 'version_submit_success'
  | 'search_name'
  | 'copy_evaluator_config'
  | 'evaluator_name'
  | 'updated_person'
  | 'update_time'
  | 'create_time'
  | 'this_operation_is_irreversible_please_operate_carefully'
  | 'failed_to_find_related_results'
  | 'try_other_keywords_or_modify_filter_options'
  | 'no_evaluator'
  | 'click_to_create'
  | 'benchmark_group'
  | 'remove_experimental_group'
  | 'evaluation_object_actual_output'
  | 'benchmark'
  | 'benchmark_experiment_switch_success'
  | 'data_detail'
  | 'measure_stat'
  | 'data_total_count'
  | 'loading_field_mapping'
  | 'select_type'
  | 'actual_output'
  | 'interface_problem'
  | 'evaluation_object_version'
  | 'config_evaluation_object_mapping'
  | 'add_at_least_one_evaluator'
  | 'max_add_x_evaluators'
  | 'name_and_version'
  | 'field_mapping'
  | 'next_step_evaluation_set'
  | 'next_step_evaluation_object'
  | 'next_step_evaluator'
  | 'confirm_experiment_config'
  | 'initiate_experiment'
  | 'new_experiment'
  | 'selected_fields_inconsistent'
  | 'evaluation_set_field_mapping_tip'
  | 'add_evaluator'
  | 'submit_form_problems'
  | 'update_rating_success'
  | 'view_evaluator_trace'
  | 'manual_calibration'
  | 'score_details'
  | 'score'
  | 'refresh_after_experiment'
  | 'aggregation_score'
  | 'score_details_data_item_distribution'
  | 'indicator'
  | 'experiment_initializing'
  | 'score_reason'
  | 'end_time'
  | 'confirm_evaluation_set_version'
  | 'draft_unsubmitted_tip'
  | 'retain_one_data_item'
  | 'collapse_all_data_items'
  | 'expand_all_data_items'
  | 'execution_result'
  | 'known'
  | 'delete_column'
  | 'column_name'
  | 'column_description'
  | 'add_column'
  | 'basic_info'
  | 'evaluation_set_name'
  | 'evaluation_set_description'
  | 'configuration_column'
  | 'can_still_modify_column'
  | 'data_type'
  | 'view_format'
  | 'no_modification_to_submit'
  | 'version_format_and_range'
  | 'click_to_add_data'
  | 'edit_evaluation_set'
  | 'import_data'
  | 'upload_data'
  | 'click_or_drag_file_to_upload'
  | 'recommend_template_upload_tip'
  | 'download_template'
  | 'upload_file'
  | 'no_mapping_no_import'
  | 'column_mapping'
  | 'source_column_mapping'
  | 'configure_at_least_one_import_column'
  | 'import_method'
  | 'no_evaluation_dataset'
  | 'click_to_create_evaluation_set'
  | 'evaluation_set_column'
  | 'configure_column_mapping'
  | 'select_import_method'
  | 'confirm_select_full_coverage'
  | 'continue_will_override_existing_data'
  | 'execution_in_progress'
  | 'number'
  | 'string'
  | 'integer'
  | 'input_float_with_precision'
  | 'edit_data_item'
  | 'view_data_item'
  | 'data_item'
  | 'delete_evaluation_set'
  | 'debug_failure'
  | 'debugging_succeeded'
  | 'prompt_detail'
  | 'loading_prompt_detail'
  | 'select_evaluator_and_version_number_to_view'
  | 'model'
  | 'output'
  | 'extract_via_function_call'
  | 'score_is'
  | 'rating'
  | 'input_score_between_0_and_1'
  | 'input_number_between_0_and_1'
  | 'reason'
  | 'view_evaluator_details'
  | 'batch_delete_experiment'
  | 'aggregate_statistics_score_on_metrics'
  | 'line_chart'
  | 'bar_chart'
  | 'no_experiment'
  | 'click_to_create_experiment'
  | 'schema_mismatch'
  | 'empty_data'
  | 'single_data_size_exceeded'
  | 'dataset_capacity_exceeded'
  | 'file_format_error'
  | 'system_error'
  | 'contains_illegal_content'
  | 'operator'
  | 'equal_to'
  | 'not_equal_to'
  | 'contain'
  | 'not_contain'
  | 'greater_than'
  | 'greater_than_or_equal_to'
  | 'less_than'
  | 'less_than_or_equal_to'
  | 'later_than'
  | 'earlier_than'
  | 'new_evaluation_set'
  | 'prompt_variable_to_ensure_effect'
  | 'new_prompt'
  | 'in_progress'
  | 'abort'
  | 'to_be_executed'
  | 'fold'
  | 're_evaluate_failed_only'
  | 'copy_and_create_experiment'
  | 'associated_evaluation_set'
  | 'delete_experiment'
  | 'retry_experiment'
  | 'only_re_evaluate_failed_part'
  | 'copy_experiment_config'
  | 'evaluation_set_field_to_evaluation_object_field_mapping'
  | 'get_evaluation_object_error'
  | 'experiments_compared_tip'
  | 'only_completed_experiments_can_be_compared'
  | 'experiment_comparison_initiation_failure'
  | 'experimental_group'
  | 'only_support_english_letters_numbers_and_chinese_at_the_beginning'
  | 'only_support_english_letters_numbers_and_chinese_and_'
  | 'only_support_english_numbers_and_underscores_and_start_with_a_letter'
  | 'current_trace_expired_to_view'
  | 'no_permission_to_view_trace'
  | 'no_permission_to_view'
  | 'reported_data_not_found'
  | 'report_in_sdk'
  | 'all_span_tip'
  | 'root_span_tip'
  | 'llm_span_tip'
  | 'confirm_delete_view'
  | 'deletion_irreversible'
  | 'default_view_not_editable'
  | 'default_view_cannot_be_deleted'
  | 'new_view_cannot_be_displayed'
  | 'viewing_method'
  | 'belong_to'
  | 'data_source'
  | 'viewing_method_data_source_linkage'
  | 'data_expiration_time'
  | 'sdk_reporting'
  | 'customize'
  | 'all_time'
  | 'not_allowed_to_be_empty'
  | 'view_name_exists'
  | 'tos_url_not_exist';
